version: 2.1
jobs:
  build:
    docker:
      - image: 'debian:stretch'
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Installing MPI libraries
          command: 'sudo apt-get install -y openmpi-bin openmpi-common openssh-client openssh-server libopenmpi2 libopenmpi-dev'
      - run:
          name: Installing Make
          command: 'apt-get update && apt-get install -y make'
      - run:
          name: Installing other dependencies
          command: 'apt-get update && apt-get install -y git curl unzip openssh-server clang build-essential unzip tar gzip python3 python3-defusedxml python3-lxml libssl-dev libffi-dev ca-certificates && apt autoclean && apt autoremove && apt clean && rm -rf /var/lib/apt/lists/*'         
      - run:
          name: Build
          command: |
            curl -L -O https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
            unzip -o build-wrapper-linux-x86.zip
            build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory make clean all
      - sonarcloud/scan
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud
